print("hello world")
print("I love Roses")
print("red roses for that matter")
print("When I see roses")
print("I smell them")
print("then I leave them be")
print("because I love roses")
print("and roses love me")
print("I do not pick")
print("I do not pluck")
print("I do not pull")
print("I leave them be to live their lives to the full")
print("good bye roses")

